// ====================================================================
// URBANRAIL_LINKS - mapy metra i kolei miejskiej (urbanrail.net)
// Przycisk METRO w panelu MIASTA (app.js, showCityIntel).
//
// KLUCZ: "<ISO2>|<dokladna nazwa z CITIES_DB[cc][n][0]>" - np. "PL|Warsaw".
// Brak wpisu = brak przycisku (wiekszosc miast nie ma kolei miejskiej).
//
// ADRESOW NIE DA SIE GENEROWAC. urbanrail nie ma regularnego wzorca sciezek:
//   /eu/pl/war/warszawa.htm   kontynent/kraj/skrot/miasto
//   /eu/de/b/berlin.htm       kontynent/kraj/LITERA/miasto
//   /am/nyrk/new-york.htm     kontynent/skrot/miasto  (BEZ kraju!)
//   /af/cairo/cairo.htm       kontynent/miasto/miasto (BEZ kraju!)
// Dlatego lista jest ZEBRANA ze strony i dopasowana do CITIES_DB skryptem
// audit\Build-UrbanRailDict.ps1 (regeneracja: patrz audit\README.md).
//
// Wygenerowane 2026-07-26 (3. przebieg, 559 wpisow - poprzedni mial 473).
// Wszystkie adresy zweryfikowane na zywo (HEAD = 200). Serwis zwraca UCZCIWE
// 404, wiec slownik da sie normalnie audytowac przez audit\Invoke-LinkAudit.ps1.
//
// DLACZEGO 2. PRZEBIEG: pierwszy dopasowywal miasta WYLACZNIE po etykiecie linku,
// a urbanrail podpisuje linki po angielsku ("Cracow", "Cologne", "Ghent") albo
// skraca nazwe ("Gorzow"). Teraz dopasowanie idzie z trzech zrodel: alias z reki,
// etykieta, SLUG Z URL-A (/eu/pl/kra/krakow.htm -> krakow). Stad +43 miasta. Trzeci przebieg dolozyl kolejne 43 po dopisaniu miast do CITIES_DB.
//
// NIEROZSTRZYGNIETE (celowo bez wpisu): brytyjskie Newcastle - CITIES_DB ma pod
// ta nazwa tylko ZA i AU (australijskie ma juz wlasny wpis z /au/newcastle/).
// Pelna lista odrzuconych: audit\raporty\urbanrail-unmatched.csv - w wiekszosci
// miasta, ktorych PO PROSTU NIE MA w CITIES_DB (Bonn, Potsdam, Yokohama, Incheon).
// ====================================================================
window.URBANRAIL_LINKS = {
    "AE|Dubai": "https://www.urbanrail.net/as/dub/dubai.htm",
    "AM|Yerevan": "https://www.urbanrail.net/as/yere/yerevan.htm",
    "AR|Buenos Aires": "https://www.urbanrail.net/am/buen/buenos-aires.htm",
    "AR|Mendoza": "https://www.urbanrail.net/am/mend/mendoza.htm",
    "AT|Gmunden": "https://www.urbanrail.net/eu/at/gmunden/gmunden.htm",
    "AT|Graz": "https://www.urbanrail.net/eu/at/graz/graz.htm",
    "AT|Innsbruck": "https://www.urbanrail.net/eu/at/innsbruck/innsbruck.htm",
    "AT|Linz": "https://www.urbanrail.net/eu/at/linz/linz.htm",
    "AT|Vienna": "https://www.urbanrail.net/eu/at/vienna/wien.htm",
    "AU|Adelaide": "https://www.urbanrail.net/au/adel/adelaide.htm",
    "AU|Brisbane": "https://www.urbanrail.net/au/bris/brisbane.htm",
    "AU|Canberra": "https://www.urbanrail.net/au/canberra/canberra.htm",
    "AU|Gold Coast": "https://www.urbanrail.net/au/goldcoast/goldcoast.htm",
    "AU|Melbourne": "https://www.urbanrail.net/au/melb/melbourne.htm",
    "AU|Newcastle": "https://www.urbanrail.net/au/newcastle/newcastle-nsw.htm",
    "AU|Perth": "https://www.urbanrail.net/au/perth/perth.htm",
    "AU|Sydney": "https://www.urbanrail.net/au/sydney/sydney.htm",
    "AZ|Baku": "https://www.urbanrail.net/as/baku/baku.htm",
    "BA|Sarajevo": "https://www.urbanrail.net/eu/ba/sarajevo/sarajevo.htm",
    "BD|Dhaka": "https://www.urbanrail.net/as/dhaka/dhaka.htm",
    "BE|Antwerp": "https://www.urbanrail.net/eu/be/ant/antwerpen.htm",
    "BE|Brussels": "https://www.urbanrail.net/eu/be/brux/brussels.htm",
    "BE|Charleroi": "https://www.urbanrail.net/eu/be/char/charleroi.htm",
    "BE|Gent": "https://www.urbanrail.net/eu/be/gent/gent.htm",
    "BE|Liege": "https://www.urbanrail.net/eu/be/liege/liege.htm",
    "BE|Ostend": "https://www.urbanrail.net/eu/be/kusttram/kusttram.htm",
    "BG|Sofia": "https://www.urbanrail.net/eu/bg/sofia/sofia.htm",
    "BO|Cochabamba": "https://www.urbanrail.net/am/cocha/cochabamba.htm",
    "BR|Belo Horizonte": "https://www.urbanrail.net/am/belo/belo-horizonte.htm",
    "BR|Brasilia": "https://www.urbanrail.net/am/bras/brasilia.htm",
    "BR|Fortaleza": "https://www.urbanrail.net/am/fort/fortaleza.htm",
    "BR|Porto Alegre": "https://www.urbanrail.net/am/ptal/porto-alegre.htm",
    "BR|Recife": "https://www.urbanrail.net/am/reci/recife.htm",
    "BR|Rio de Janeiro": "https://www.urbanrail.net/am/rioj/rio-de-janeiro.htm",
    "BR|Salvador": "https://www.urbanrail.net/am/salv/salvador.htm",
    "BR|Santos": "https://www.urbanrail.net/am/santos/santos.htm",
    "BR|Sao Paulo": "https://www.urbanrail.net/am/spau/sao-paulo.htm",
    "BY|Mazyr": "https://www.urbanrail.net/eu/by/mazyr/mazyr.htm",
    "BY|Minsk": "https://www.urbanrail.net/eu/by/minsk/minsk.htm",
    "BY|Novopolotsk": "https://www.urbanrail.net/eu/by/navapolatsk/navapolatsk.htm",
    "BY|Vitebsk": "https://www.urbanrail.net/eu/by/vitsebsk/vitsebsk.htm",
    "CA|Calgary": "https://www.urbanrail.net/am/calg/calgary.htm",
    "CA|Edmonton": "https://www.urbanrail.net/am/edmo/edmonton.htm",
    "CA|Hamilton": "https://www.urbanrail.net/am/hamilton/hamilton.htm",
    "CA|Mississauga": "https://www.urbanrail.net/am/toro/mississauga.htm",
    "CA|Montreal": "https://www.urbanrail.net/am/monr/montreal.htm",
    "CA|Ottawa": "https://www.urbanrail.net/am/ottawa/ottawa.htm",
    "CA|Quebec": "https://www.urbanrail.net/am/quebec/quebec.htm",
    "CA|Toronto": "https://www.urbanrail.net/am/toro/toronto.htm",
    "CA|Vancouver": "https://www.urbanrail.net/am/vanc/vancouver.htm",
    "CA|Waterloo": "https://www.urbanrail.net/am/waterloo/waterloo-region.htm",
    "CH|Basel": "https://www.urbanrail.net/eu/ch/bs/basel.htm",
    "CH|Bern": "https://www.urbanrail.net/eu/ch/be/bern.htm",
    "CH|Geneva": "https://www.urbanrail.net/eu/ch/ge/geneve.htm",
    "CH|Lausanne": "https://www.urbanrail.net/eu/ch/vd/lausanne.htm",
    "CH|Neuchatel": "https://www.urbanrail.net/eu/ch/ne/neuchatel.htm",
    "CH|Zuerich": "https://www.urbanrail.net/eu/ch/zh/zuerich.htm",
    "CL|Santiago": "https://www.urbanrail.net/am/sant/santiago.htm",
    "CL|Valparaiso": "https://www.urbanrail.net/am/valp/valparaiso.htm",
    "CN|Beijing": "https://www.urbanrail.net/as/cn/beij/beijing.htm",
    "CN|Changchun": "https://www.urbanrail.net/as/cn/chan/changchun.htm",
    "CN|Changsha": "https://www.urbanrail.net/as/cn/changsha/changsha.htm",
    "CN|Changzhou": "https://www.urbanrail.net/as/cn/changzhou/changzhou.htm",
    "CN|Chengdu": "https://www.urbanrail.net/as/cn/chdu/chengdu.htm",
    "CN|Chongqing": "https://www.urbanrail.net/as/cn/chon/chongqing.htm",
    "CN|Dalian": "https://www.urbanrail.net/as/cn/dalian/dalian.htm",
    "CN|Dongguan": "https://www.urbanrail.net/as/cn/dongguan/dongguan.htm",
    "CN|Foshan": "https://www.urbanrail.net/as/cn/guan/foshan.htm",
    "CN|Fuzhou": "https://www.urbanrail.net/as/cn/fuzhou/fuzhou.htm",
    "CN|Guangzhou": "https://www.urbanrail.net/as/cn/guan/guangzhou.htm",
    "CN|Guiyang": "https://www.urbanrail.net/as/cn/guiyang/guiyang.htm",
    "CN|Hangzhou": "https://www.urbanrail.net/as/cn/hang/hangzhou.htm",
    "CN|Harbin": "https://www.urbanrail.net/as/cn/harbin/harbin.htm",
    "CN|Hefei": "https://www.urbanrail.net/as/cn/hefei/hefei.htm",
    "CN|Hohhot": "https://www.urbanrail.net/as/cn/hohhot/hohhot.htm",
    "CN|Jinan": "https://www.urbanrail.net/as/cn/jinan/jinan.htm",
    "CN|Jinhua": "https://www.urbanrail.net/as/cn/jinhua/jinhua.htm",
    "CN|Kunming": "https://www.urbanrail.net/as/cn/kunming/kunming.htm",
    "CN|Lanzhou": "https://www.urbanrail.net/as/cn/lanzhou/lanzhou.htm",
    "CN|Luoyang": "https://www.urbanrail.net/as/cn/luoyang/luoyang.htm",
    "CN|Nanchang": "https://www.urbanrail.net/as/cn/nanchang/nanchang.htm",
    "CN|Nanjing": "https://www.urbanrail.net/as/cn/nanj/nanjing.htm",
    "CN|Nanning": "https://www.urbanrail.net/as/cn/nanning/nanning.htm",
    "CN|Nantong": "https://www.urbanrail.net/as/cn/nantong/nantong.htm",
    "CN|Ningbo": "https://www.urbanrail.net/as/cn/ningbo/ningbo.htm",
    "CN|Qingdao": "https://www.urbanrail.net/as/cn/qing/qingdao.htm",
    "CN|Shanghai": "https://www.urbanrail.net/as/cn/shan/shanghai.htm",
    "CN|Shaoxing": "https://www.urbanrail.net/as/cn/shaoxing/shaoxing.htm",
    "CN|Shenyang": "https://www.urbanrail.net/as/cn/shny/shenyang.htm",
    "CN|Shenzhen": "https://www.urbanrail.net/as/cn/shen/shenzhen.htm",
    "CN|Shijiazhuang": "https://www.urbanrail.net/as/cn/shijiazhuang/shijiazhuang.htm",
    "CN|Suzhou": "https://www.urbanrail.net/as/cn/suzh/suzhou.htm",
    "CN|Taiyuan": "https://www.urbanrail.net/as/cn/taiyuan/taiyuan.htm",
    "CN|Taizhou": "https://www.urbanrail.net/as/cn/taizhou/taizhou.htm",
    "CN|Tianjin": "https://www.urbanrail.net/as/cn/tian/tianjin.htm",
    "CN|Tianshui": "https://www.urbanrail.net/as/cn/tianshui/tianshui.htm",
    "CN|UEruemqi": "https://www.urbanrail.net/as/cn/urumqi/urumqi.htm",
    "CN|Wenzhou": "https://www.urbanrail.net/as/cn/wenzhou/wenzhou.htm",
    "CN|Wuhan": "https://www.urbanrail.net/as/cn/wuhan/wuhan.htm",
    "CN|Wuhu": "https://www.urbanrail.net/as/cn/wuhu/wuhu.htm",
    "CN|Wuxi": "https://www.urbanrail.net/as/cn/wuxi/wuxi.htm",
    "CN|Xiamen": "https://www.urbanrail.net/as/cn/xiamen/xiamen.htm",
    "CN|Xi'an": "https://www.urbanrail.net/as/cn/xian/xian.htm",
    "CN|Xuzhou": "https://www.urbanrail.net/as/cn/xuzhou/xuzhou.htm",
    "CN|Zhengzhou": "https://www.urbanrail.net/as/cn/zheng/zhengzhou.htm",
    "CN|Zhuhai": "https://www.urbanrail.net/as/cn/zhuhai/zhuhai.htm",
    "CO|Bogota": "https://www.urbanrail.net/am/bogota/bogota.htm",
    "CO|Medellin": "https://www.urbanrail.net/am/mede/medellin.htm",
    "CZ|Brno": "https://www.urbanrail.net/eu/cz/brno/brno.htm",
    "CZ|Liberec": "https://www.urbanrail.net/eu/cz/liberec/liberec.htm",
    "CZ|Most": "https://www.urbanrail.net/eu/cz/most/most.htm",
    "CZ|Olomouc": "https://www.urbanrail.net/eu/cz/olomouc/olomouc.htm",
    "CZ|Ostrava": "https://www.urbanrail.net/eu/cz/ostrava/ostrava.htm",
    "CZ|Pilsen": "https://www.urbanrail.net/eu/cz/plzen/plzen.htm",
    "CZ|Prague": "https://www.urbanrail.net/eu/cz/praha/praha.htm",
    "DE|Augsburg": "https://www.urbanrail.net/eu/de/a/augsburg.htm",
    "DE|Berlin": "https://www.urbanrail.net/eu/de/b/berlin.htm",
    "DE|Bielefeld": "https://www.urbanrail.net/eu/de/bi/bielefeld.htm",
    "DE|Bonn": "https://www.urbanrail.net/eu/de/bn/bonn.htm",
    "DE|Brandenburg an der Havel": "https://www.urbanrail.net/eu/de/brb/brandenburg-havel.htm",
    "DE|Braunschweig": "https://www.urbanrail.net/eu/de/bs/braunschweig.htm",
    "DE|Bremen": "https://www.urbanrail.net/eu/de/hb/bremen.htm",
    "DE|Chemnitz": "https://www.urbanrail.net/eu/de/c/chemnitz.htm",
    "DE|Cottbus": "https://www.urbanrail.net/eu/de/cb/cottbus.htm",
    "DE|Darmstadt": "https://www.urbanrail.net/eu/de/da/darmstadt.htm",
    "DE|Dessau": "https://www.urbanrail.net/eu/de/de/dessau.htm",
    "DE|Dortmund": "https://www.urbanrail.net/eu/de/do/dortmund.htm",
    "DE|Dresden": "https://www.urbanrail.net/eu/de/dd/dresden.htm",
    "DE|Duesseldorf": "https://www.urbanrail.net/eu/de/d/duesseldorf.htm",
    "DE|Duisburg": "https://www.urbanrail.net/eu/de/du/duisburg.htm",
    "DE|Erfurt": "https://www.urbanrail.net/eu/de/ef/erfurt.htm",
    "DE|Essen": "https://www.urbanrail.net/eu/de/e/essen.htm",
    "DE|Frankfurt (Oder)": "https://www.urbanrail.net/eu/de/ff/frankfurt-oder.htm",
    "DE|Frankfurt am Main": "https://www.urbanrail.net/eu/de/f/frankfurt.htm",
    "DE|Freiburg": "https://www.urbanrail.net/eu/de/fr/freiburg.htm",
    "DE|Gelsenkirchen": "https://www.urbanrail.net/eu/de/bo/bochum.htm",
    "DE|Gera": "https://www.urbanrail.net/eu/de/g/gera.htm",
    "DE|Goerlitz": "https://www.urbanrail.net/eu/de/gr/goerlitz.htm",
    "DE|Gotha": "https://www.urbanrail.net/eu/de/gth/gotha.htm",
    "DE|Halberstadt": "https://www.urbanrail.net/eu/de/hbs/halberstadt.htm",
    "DE|Halle (Saale)": "https://www.urbanrail.net/eu/de/hal/halle-saale.htm",
    "DE|Hamburg": "https://www.urbanrail.net/eu/de/hh/hamburg.htm",
    "DE|Hannover": "https://www.urbanrail.net/eu/de/h/hannover.htm",
    "DE|Heidelberg": "https://www.urbanrail.net/eu/de/hd/heidelberg.htm",
    "DE|Heilbronn": "https://www.urbanrail.net/eu/de/hn/heilbronn.htm",
    "DE|Jena": "https://www.urbanrail.net/eu/de/j/jena.htm",
    "DE|Karlsruhe": "https://www.urbanrail.net/eu/de/ka/karlsruhe.htm",
    "DE|Kassel": "https://www.urbanrail.net/eu/de/ks/kassel.htm",
    "DE|Koeln": "https://www.urbanrail.net/eu/de/k/koeln.htm",
    "DE|Krefeld": "https://www.urbanrail.net/eu/de/kr/krefeld.htm",
    "DE|Leipzig": "https://www.urbanrail.net/eu/de/l/leipzig.htm",
    "DE|Ludwigshafen am Rhein": "https://www.urbanrail.net/eu/de/lu/ludwigshafen.htm",
    "DE|Magdeburg": "https://www.urbanrail.net/eu/de/md/magdeburg.htm",
    "DE|Mainz": "https://www.urbanrail.net/eu/de/mz/mainz.htm",
    "DE|Mannheim": "https://www.urbanrail.net/eu/de/ma/mannheim.htm",
    "DE|Munich": "https://www.urbanrail.net/eu/de/m/muenchen.htm",
    "DE|Naumburg": "https://www.urbanrail.net/eu/de/nmb/naumburg.htm",
    "DE|Nordhausen": "https://www.urbanrail.net/eu/de/ndh/nordhausen.htm",
    "DE|Nuremberg": "https://www.urbanrail.net/eu/de/n/nuernberg.htm",
    "DE|Plauen": "https://www.urbanrail.net/eu/de/pl/plauen.htm",
    "DE|Potsdam": "https://www.urbanrail.net/eu/de/p/potsdam.htm",
    "DE|Rostock": "https://www.urbanrail.net/eu/de/hro/rostock.htm",
    "DE|Saarbruecken": "https://www.urbanrail.net/eu/de/sb/saarbruecken.htm",
    "DE|Schwerin": "https://www.urbanrail.net/eu/de/sn/schwerin.htm",
    "DE|Strausberg": "https://www.urbanrail.net/eu/de/mol/strausberg.htm",
    "DE|Stuttgart": "https://www.urbanrail.net/eu/de/s/stuttgart.htm",
    "DE|Ulm": "https://www.urbanrail.net/eu/de/ul/ulm.htm",
    "DE|Wuerzburg": "https://www.urbanrail.net/eu/de/wue/wuerzburg.htm",
    "DE|Wuppertal": "https://www.urbanrail.net/eu/de/w/wuppertal.htm",
    "DE|Zwickau": "https://www.urbanrail.net/eu/de/z/zwickau.htm",
    "DK|Arhus": "https://www.urbanrail.net/eu/dk/aarhus/aarhus.htm",
    "DK|Copenhagen": "https://www.urbanrail.net/eu/dk/kobenhavn/kobenhavn.htm",
    "DK|Odense": "https://www.urbanrail.net/eu/dk/odense/odense.htm",
    "DO|Santiago de los Caballeros": "https://www.urbanrail.net/am/santiago-cab/santiago-de-los-caballeros.htm",
    "DO|Santo Domingo": "https://www.urbanrail.net/am/sdom/santo-domingo.htm",
    "DZ|Algiers": "https://www.urbanrail.net/af/alg/algiers.htm",
    "DZ|Annaba": "https://www.urbanrail.net/af/annaba/annaba.htm",
    "DZ|Batna": "https://www.urbanrail.net/af/batna/batna.htm",
    "DZ|Constantine": "https://www.urbanrail.net/af/const/constantine.htm",
    "DZ|Mostaganem": "https://www.urbanrail.net/af/mostaganem/mostaganem.htm",
    "DZ|Oran": "https://www.urbanrail.net/af/oran/oran.htm",
    "DZ|Ouargla": "https://www.urbanrail.net/af/ouargla/ouargla.htm",
    "DZ|Setif": "https://www.urbanrail.net/af/setif/setif.htm",
    "DZ|Sidi Bel Abbes": "https://www.urbanrail.net/af/sidi-bel-abbes/sidi-bel-abbes.htm",
    "EC|Cuenca": "https://www.urbanrail.net/am/cuenca/cuenca.htm",
    "EC|Quito": "https://www.urbanrail.net/am/quito/quito.htm",
    "EE|Tallinn": "https://www.urbanrail.net/eu/ee/tallinn/tallinn.htm",
    "EG|Alexandria": "https://www.urbanrail.net/af/alex/alexandria.htm",
    "EG|Cairo": "https://www.urbanrail.net/af/cairo/cairo.htm",
    "ES|Alicante": "https://www.urbanrail.net/eu/es/alicante/alacant.htm",
    "ES|Barcelona": "https://www.urbanrail.net/eu/es/bcn/barcelona.htm",
    "ES|Bilbao": "https://www.urbanrail.net/eu/es/bilbao/bilbao.htm",
    "ES|Cadiz": "https://www.urbanrail.net/eu/es/cadiz/cadiz.htm",
    "ES|Gasteiz / Vitoria": "https://www.urbanrail.net/eu/es/vitoria/vitoria-gasteiz.htm",
    "ES|Granada": "https://www.urbanrail.net/eu/es/granada/granada.htm",
    "ES|Jaen": "https://www.urbanrail.net/eu/es/jaen/jaen.htm",
    "ES|Madrid": "https://www.urbanrail.net/eu/es/mad/madrid.htm",
    "ES|Malaga": "https://www.urbanrail.net/eu/es/malaga/malaga.htm",
    "ES|Murcia": "https://www.urbanrail.net/eu/es/murcia/murcia.htm",
    "ES|Palma": "https://www.urbanrail.net/eu/es/palma/palma.htm",
    "ES|Parla": "https://www.urbanrail.net/eu/es/parla/parla.htm",
    "ES|San Sebastian": "https://www.urbanrail.net/eu/es/doss/donostia.htm",
    "ES|Santa Cruz de Tenerife": "https://www.urbanrail.net/eu/es/tenerife/tenerife.htm",
    "ES|Sevilla": "https://www.urbanrail.net/eu/es/sevilla/sevilla.htm",
    "ES|Soller": "https://www.urbanrail.net/eu/es/soller/soller.htm",
    "ES|Tarragona": "https://www.urbanrail.net/eu/es/tarragona/camp-de-tarragona.htm",
    "ES|Velez-Malaga": "https://www.urbanrail.net/eu/es/malaga/velez-malaga.htm",
    "ES|Zaragoza": "https://www.urbanrail.net/eu/es/zara/zaragoza.htm",
    "ET|Addis Ababa": "https://www.urbanrail.net/af/addis-ababa/addis-ababa.htm",
    "FI|Helsinki": "https://www.urbanrail.net/eu/fi/helsinki//helsinki.htm",
    "FI|Tampere": "https://www.urbanrail.net/eu/fi/tampere/tampere.htm",
    "FR|Angers": "https://www.urbanrail.net/eu/fr/angers/angers.htm",
    "FR|Aubagne": "https://www.urbanrail.net/eu/fr/aubagne/aubagne.htm",
    "FR|Avignon": "https://www.urbanrail.net/eu/fr/avignon/avignon.htm",
    "FR|Besancon": "https://www.urbanrail.net/eu/fr/besancon/besancon.htm",
    "FR|Bordeaux": "https://www.urbanrail.net/eu/fr/bordeaux/bordeaux-tram.htm",
    "FR|Brest": "https://www.urbanrail.net/eu/fr/brest/brest.htm",
    "FR|Caen": "https://www.urbanrail.net/eu/fr/caen/caen-tram.htm",
    "FR|Clermont-Ferrand": "https://www.urbanrail.net/eu/fr/clermont-ferrand/clermont-ferrand-tram.htm",
    "FR|Dijon": "https://www.urbanrail.net/eu/fr/dijon/dijon.htm",
    "FR|Grenoble": "https://www.urbanrail.net/eu/fr/grenoble/grenoble-tram.htm",
    "FR|Le Havre": "https://www.urbanrail.net/eu/fr/le-havre/le-havre.htm",
    "FR|Le Mans": "https://www.urbanrail.net/eu/fr/le-mans/le-mans-tram.htm",
    "FR|Lille": "https://www.urbanrail.net/eu/fr/lille/lille.htm",
    "FR|Lyon": "https://www.urbanrail.net/eu/fr/lyon/lyon.htm",
    "FR|Marseille": "https://www.urbanrail.net/eu/fr/marseille/marseille.htm",
    "FR|Montpellier": "https://www.urbanrail.net/eu/fr/montpellier/montpellier-tram.htm",
    "FR|Mulhouse": "https://www.urbanrail.net/eu/fr/mulhouse/mulhouse-tram.htm",
    "FR|Nantes": "https://www.urbanrail.net/eu/fr/nantes/nantes-tram.htm",
    "FR|Nice": "https://www.urbanrail.net/eu/fr/nice/nice-tram.htm",
    "FR|Orleans": "https://www.urbanrail.net/eu/fr/orleans/orleans-tram.htm",
    "FR|Paris": "https://www.urbanrail.net/eu/fr/paris/paris.htm",
    "FR|Reims": "https://www.urbanrail.net/eu/fr/reims/reims.htm",
    "FR|Rennes": "https://www.urbanrail.net/eu/fr/rennes/rennes.htm",
    "FR|Rouen": "https://www.urbanrail.net/eu/fr/rouen/rouen-tram.htm",
    "FR|Saint-Etienne": "https://www.urbanrail.net/eu/fr/saint-etienne/saint-etienne-tram.htm",
    "FR|Strasbourg": "https://www.urbanrail.net/eu/fr/strasbourg/strasbourg-tram.htm",
    "FR|Toulouse": "https://www.urbanrail.net/eu/fr/toulouse/toulouse.htm",
    "FR|Tours": "https://www.urbanrail.net/eu/fr/tours/tours.htm",
    "FR|Valenciennes": "https://www.urbanrail.net/eu/fr/valenciennes/valenciennes-tram.htm",
    "GB|Birmingham": "https://www.urbanrail.net/eu/uk/bir/birmingham.htm",
    "GB|Blackpool": "https://www.urbanrail.net/eu/uk/black/blackpool.htm",
    "GB|Edinburgh": "https://www.urbanrail.net/eu/uk/edin/edinburgh.htm",
    "GB|Glasgow": "https://www.urbanrail.net/eu/uk/gla/glasgow.htm",
    "GB|London": "https://www.urbanrail.net/eu/uk/lon/london.htm",
    "GB|Manchester": "https://www.urbanrail.net/eu/uk/man/manchester.htm",
    "GB|Nottingham": "https://www.urbanrail.net/eu/uk/nott/nottingham.htm",
    "GB|Sheffield": "https://www.urbanrail.net/eu/uk/sheff/sheffield.htm",
    "GE|Tbilisi": "https://www.urbanrail.net/as/tbil/tbilisi.htm",
    "GR|Athens": "https://www.urbanrail.net/eu/gr/athens/athens.htm",
    "GR|Thessaloniki": "https://www.urbanrail.net/eu/gr/thessaloniki/thessaloniki.htm",
    "HK|Hong Kong": "https://www.urbanrail.net/as/cn/hong/hong-kong.htm",
    "HR|Osijek": "https://www.urbanrail.net/eu/hr/osijek/osijek.htm",
    "HR|Zagreb": "https://www.urbanrail.net/eu/hr/zagreb/zagreb.htm",
    "HU|Budapest": "https://www.urbanrail.net/eu/hu/budapest/budapest.htm",
    "HU|Debrecen": "https://www.urbanrail.net/eu/hu/debrecen/debrecen.htm",
    "HU|Miskolc": "https://www.urbanrail.net/eu/hu/miskolc/miskolc.htm",
    "HU|Szeged": "https://www.urbanrail.net/eu/hu/szeged/szeged.htm",
    "ID|Jakarta": "https://www.urbanrail.net/as/id/jaka/jakarta.htm",
    "ID|Palembang": "https://www.urbanrail.net/as/id/palem/palembang.htm",
    "IE|Dublin": "https://www.urbanrail.net/eu/ie/dublin/dublin.htm",
    "IL|Haifa": "https://www.urbanrail.net/as/il/hai/haifa.htm",
    "IL|Jerusalem": "https://www.urbanrail.net/as/il/jeru/jerusalem.htm",
    "IL|Tel Aviv": "https://www.urbanrail.net/as/il/tlav/tel-aviv.htm",
    "IN|Agra": "https://www.urbanrail.net/as/in/agra/agra.htm",
    "IN|Ahmedabad": "https://www.urbanrail.net/as/in/ahmedabad/ahmedabad.htm",
    "IN|Bengaluru": "https://www.urbanrail.net/as/in/banl/bangalore.htm",
    "IN|Bhopal": "https://www.urbanrail.net/as/in/bhopal/bhopal.htm",
    "IN|Chennai": "https://www.urbanrail.net/as/in/chen/chennai.htm",
    "IN|Delhi": "https://www.urbanrail.net/as/in/delhi/delhi.htm",
    "IN|Hyderabad": "https://www.urbanrail.net/as/in/hydr/hyderabad.htm",
    "IN|Indore": "https://www.urbanrail.net/as/in/indore/indore.htm",
    "IN|Jaipur": "https://www.urbanrail.net/as/in/jaip/jaipur.htm",
    "IN|Kanpur": "https://www.urbanrail.net/as/in/kanpur/kanpur.htm",
    "IN|Kochi": "https://www.urbanrail.net/as/in/kochi/kochi.htm",
    "IN|Kolkata": "https://www.urbanrail.net/as/in/kolk/kolkata.htm",
    "IN|Lucknow": "https://www.urbanrail.net/as/in/lucknow/lucknow.htm",
    "IN|Meerut": "https://www.urbanrail.net/as/in/delhi/meerut-metro.htm",
    "IN|Mumbai": "https://www.urbanrail.net/as/in/mumb/mumbai.htm",
    "IN|Nagpur": "https://www.urbanrail.net/as/in/nagpur/nagpur.htm",
    "IN|Navi Mumbai": "https://www.urbanrail.net/as/in/mumb/navi-mumbai.htm",
    "IN|Patna": "https://www.urbanrail.net/as/in/patna/patna.htm",
    "IN|Pune": "https://www.urbanrail.net/as/in/pune/pune.htm",
    "IR|Isfahan": "https://www.urbanrail.net/as/ir/isfa/isfahan.htm",
    "IR|Karaj": "https://www.urbanrail.net/as/ir/karaj/karaj.htm",
    "IR|Kermanshah": "https://www.urbanrail.net/as/ir/kermanshah/kermanshah.htm",
    "IR|Mashhad": "https://www.urbanrail.net/as/ir/mash/mashhad.htm",
    "IR|Qom": "https://www.urbanrail.net/as/ir/qom/qom.htm",
    "IR|Shiraz": "https://www.urbanrail.net/as/ir/shir/shiraz.htm",
    "IR|Tabriz": "https://www.urbanrail.net/as/ir/tabr/tabriz.htm",
    "IR|Tehran": "https://www.urbanrail.net/as/ir/tehr/tehran.htm",
    "IT|Bergamo": "https://www.urbanrail.net/eu/it/berg/bergamo.htm",
    "IT|Bologna": "https://www.urbanrail.net/eu/it/bol/bologna.htm",
    "IT|Brescia": "https://www.urbanrail.net/eu/it/bre/brescia.htm",
    "IT|Cagliari": "https://www.urbanrail.net/eu/it/cagl/cagliari.htm",
    "IT|Catania": "https://www.urbanrail.net/eu/it/cat/catania.htm",
    "IT|Florence": "https://www.urbanrail.net/eu/it/fir/firenze.htm",
    "IT|Genoa": "https://www.urbanrail.net/eu/it/gen/genova.htm",
    "IT|Messina": "https://www.urbanrail.net/eu/it/mess/messina.htm",
    "IT|Milan": "https://www.urbanrail.net/eu/it/mil/milano.htm",
    "IT|Naples": "https://www.urbanrail.net/eu/it/nap/napoli.htm",
    "IT|Padua": "https://www.urbanrail.net/eu/it/pad/padova.htm",
    "IT|Palermo": "https://www.urbanrail.net/eu/it/pal/palermo.htm",
    "IT|Perugia": "https://www.urbanrail.net/eu/it/per/perugia.htm",
    "IT|Rome": "https://www.urbanrail.net/eu/it/rom/roma.htm",
    "IT|Sassari": "https://www.urbanrail.net/eu/it/sass/sassari.htm",
    "IT|Trieste": "https://www.urbanrail.net/eu/it/tri/trieste.htm",
    "IT|Turin": "https://www.urbanrail.net/eu/it/tor/torino.htm",
    "IT|Venice": "https://www.urbanrail.net/eu/it/venezia/venezia-mestre.htm",
    "JP|Chiba": "https://www.urbanrail.net/as/jp/chiba/chiba.htm",
    "JP|Fujisawa": "https://www.urbanrail.net/as/jp/shonan/shonan.htm",
    "JP|Fukui-shi": "https://www.urbanrail.net/as/jp/fukui/fukui.htm",
    "JP|Fukuoka": "https://www.urbanrail.net/as/jp/fukuoka/fukuoka.htm",
    "JP|Hakodate": "https://www.urbanrail.net/as/jp/hakodate/hakodate.htm",
    "JP|Hiroshima": "https://www.urbanrail.net/as/jp/hiroshima/hiroshima.htm",
    "JP|Kagoshima": "https://www.urbanrail.net/as/jp/kagoshima/kagoshima.htm",
    "JP|Kitakyushu": "https://www.urbanrail.net/as/jp/kitakyushu/kitakyushu.htm",
    "JP|Kobe": "https://www.urbanrail.net/as/jp/kobe/kobe.htm",
    "JP|Kumamoto": "https://www.urbanrail.net/as/jp/kumamoto/kumamoto.htm",
    "JP|Kyoto": "https://www.urbanrail.net/as/jp/kyoto/kyoto.htm",
    "JP|Matsuyama": "https://www.urbanrail.net/as/jp/matsuyama/matsuyama.htm",
    "JP|Nagasaki": "https://www.urbanrail.net/as/jp/nagasaki/nagasaki.htm",
    "JP|Nagoya": "https://www.urbanrail.net/as/jp/nagoya/nagoya.htm",
    "JP|Naha": "https://www.urbanrail.net/as/jp/naha/naha.htm",
    "JP|Okayama": "https://www.urbanrail.net/as/jp/okayama/okayama.htm",
    "JP|Osaka": "https://www.urbanrail.net/as/jp/osaka/osaka.htm",
    "JP|Sapporo": "https://www.urbanrail.net/as/jp/sapporo/sapporo.htm",
    "JP|Sendai": "https://www.urbanrail.net/as/jp/sendai/sendai.htm",
    "JP|Takaoka": "https://www.urbanrail.net/as/jp/takaoka/takaoka.htm",
    "JP|Tama": "https://www.urbanrail.net/as/jp/tama/tama.htm",
    "JP|Tokyo": "https://www.urbanrail.net/as/jp/tokyo/tokyo.htm",
    "JP|Toyama": "https://www.urbanrail.net/as/jp/toyama/toyama.htm",
    "JP|Toyohashi": "https://www.urbanrail.net/as/jp/toyohashi/toyohashi.htm",
    "JP|Utsunomiya": "https://www.urbanrail.net/as/jp/utsunomiya/utsunomiya.htm",
    "JP|Yokohama": "https://www.urbanrail.net/as/jp/yokohama/yokohama.htm",
    "KP|Chongjin": "https://www.urbanrail.net/as/kr/chongjin/chongjin.htm",
    "KP|Pyongyang": "https://www.urbanrail.net/as/kr/pyongyang/pyongyang.htm",
    "KR|Busan": "https://www.urbanrail.net/as/kr/busan/busan.htm",
    "KR|Daegu": "https://www.urbanrail.net/as/kr/daegu/daegu.htm",
    "KR|Daejeon": "https://www.urbanrail.net/as/kr/daejeon/daejeon.htm",
    "KR|Gwangju": "https://www.urbanrail.net/as/kr/gwangju/gwangju.htm",
    "KR|Incheon": "https://www.urbanrail.net/as/kr/incheon/incheon.htm",
    "KR|Seoul": "https://www.urbanrail.net/as/kr/seoul/seoul.htm",
    "KR|Uijeongbu": "https://www.urbanrail.net/as/kr/uijeongbu/uijeongbu.htm",
    "KZ|Almaty": "https://www.urbanrail.net/as/kz/almaty/almaty.htm",
    "KZ|Astana": "https://www.urbanrail.net/as/kz/astana/astana.htm",
    "KZ|Pavlodar": "https://www.urbanrail.net/as/kz/pavlodar/pavlodar.htm",
    "KZ|Temirtau": "https://www.urbanrail.net/as/kz/temirtau/temirtau.htm",
    "KZ|Ust-Kamenogorsk": "https://www.urbanrail.net/as/kz/oskemen/oskemen.htm",
    "LU|Luxembourg": "https://www.urbanrail.net/eu/lu/luxembourg.htm",
    "LV|Daugavpils": "https://www.urbanrail.net/eu/lv/dauga/daugavpils.htm",
    "LV|Liepaja": "https://www.urbanrail.net/eu/lv/liepa/liepaja.htm",
    "LV|Riga": "https://www.urbanrail.net/eu/lv/riga/riga.htm",
    "MA|Casablanca": "https://www.urbanrail.net/af/casa/casablanca.htm",
    "MA|Rabat": "https://www.urbanrail.net/af/rabat/rabat.htm",
    "MO|Macau": "https://www.urbanrail.net/as/cn/macau/macau.htm",
    "MU|Port Louis": "https://www.urbanrail.net/af/mauritius/maurice.htm",
    "MX|Guadalajara": "https://www.urbanrail.net/am/guad/guadalajara.htm",
    "MX|Monterrey": "https://www.urbanrail.net/am/mony/monterrey.htm",
    "MY|George Town": "https://www.urbanrail.net/as/my/penang/penang.htm",
    "MY|Kuala Lumpur": "https://www.urbanrail.net/as/my/kual/kuala-lumpur.htm",
    "NG|Abuja": "https://www.urbanrail.net/af/abuja/abuja.htm",
    "NG|Lagos": "https://www.urbanrail.net/af/lagos/lagos.htm",
    "NL|Amsterdam": "https://www.urbanrail.net/eu/nl/ams/amsterdam.htm",
    "NL|Rotterdam": "https://www.urbanrail.net/eu/nl/rot/rotterdam.htm",
    "NL|The Hague": "https://www.urbanrail.net/eu/nl/dhg/den-haag.htm",
    "NL|Utrecht": "https://www.urbanrail.net/eu/nl/utr/utrecht.htm",
    "NO|Bergen": "https://www.urbanrail.net/eu/no/bergen/bergen.htm",
    "NO|Oslo": "https://www.urbanrail.net/eu/no/oslo/oslo.htm",
    "NO|Trondheim": "https://www.urbanrail.net/eu/no/trondheim/trondheim.htm",
    "NZ|Auckland": "https://www.urbanrail.net/au/auck/auckland.htm",
    "NZ|Wellington": "https://www.urbanrail.net/au/well/wellington.htm",
    "PA|Panama City": "https://www.urbanrail.net/am/pana/panama.htm",
    "PE|Lima": "https://www.urbanrail.net/am/lima/lima.htm",
    "PH|Manila": "https://www.urbanrail.net/as/manila/manila.htm",
    "PK|Lahore": "https://www.urbanrail.net/as/lahore/lahore.htm",
    "PL|Bydgoszcz": "https://www.urbanrail.net/eu/pl/bydg/bydgoszcz.htm",
    "PL|Czestochowa": "https://www.urbanrail.net/eu/pl/czestochowa/czestochowa.htm",
    "PL|Elblag": "https://www.urbanrail.net/eu/pl/elblg/elblag.htm",
    "PL|Gdansk": "https://www.urbanrail.net/eu/pl/gdan/gdansk-tram.htm",
    "PL|Gorzow Wielkopolski": "https://www.urbanrail.net/eu/pl/gorzow/gorzow.htm",
    "PL|Grudziadz": "https://www.urbanrail.net/eu/pl/grudz/grudziadz.htm",
    "PL|Katowice": "https://www.urbanrail.net/eu/pl/katow/katowice.htm",
    "PL|Krakow": "https://www.urbanrail.net/eu/pl/kra/krakow.htm",
    "PL|Lodz": "https://www.urbanrail.net/eu/pl/lodz/lodz.htm",
    "PL|Olsztyn": "https://www.urbanrail.net/eu/pl/olsztyn/olsztyn.htm",
    "PL|Poznan": "https://www.urbanrail.net/eu/pl/poz/poznan.htm",
    "PL|Szczecin": "https://www.urbanrail.net/eu/pl/szczn/szczecin.htm",
    "PL|Torun": "https://www.urbanrail.net/eu/pl/torun/torun.htm",
    "PL|Warsaw": "https://www.urbanrail.net/eu/pl/war/warszawa.htm",
    "PL|Wroclaw": "https://www.urbanrail.net/eu/pl/wroc/wroclaw.htm",
    "PR|San Juan": "https://www.urbanrail.net/am/snju/san-juan.htm",
    "PT|Almada": "https://www.urbanrail.net/eu/pt/lisboa/almada.htm",
    "PT|Lisbon": "https://www.urbanrail.net/eu/pt/lisboa/lisboa.htm",
    "PT|Porto": "https://www.urbanrail.net/eu/pt/porto/porto.htm",
    "PT|Sintra": "https://www.urbanrail.net/eu/pt/sintra/sintra.htm",
    "QA|Doha": "https://www.urbanrail.net/as/doha/doha.htm",
    "RO|Arad": "https://www.urbanrail.net/eu/ro/arad/arad.htm",
    "RO|Botosani": "https://www.urbanrail.net/eu/ro/botosani/botosani.htm",
    "RO|Braila": "https://www.urbanrail.net/eu/ro/braila/braila.htm",
    "RO|Bucharest": "https://www.urbanrail.net/eu/ro/buc/bucurest.htm",
    "RO|Cluj-Napoca": "https://www.urbanrail.net/eu/ro/cluj/cluj-napoca.htm",
    "RO|Craiova": "https://www.urbanrail.net/eu/ro/craiova/craiova.htm",
    "RO|Galati": "https://www.urbanrail.net/eu/ro/galati/galati.htm",
    "RO|Iasi": "https://www.urbanrail.net/eu/ro/iasi/iasi.htm",
    "RO|Oradea": "https://www.urbanrail.net/eu/ro/oradea/oradea.htm",
    "RO|Ploiesti": "https://www.urbanrail.net/eu/ro/ploiesti/ploiesti.htm",
    "RO|Resita": "https://www.urbanrail.net/eu/ro/resita/resita.htm",
    "RO|Timisoara": "https://www.urbanrail.net/eu/ro/timisoara/timisoara.htm",
    "RS|Belgrade": "https://www.urbanrail.net/eu/rs/beograd/beograd.htm",
    "RU|Achinsk": "https://www.urbanrail.net/eu/ru/achinsk/achinsk.htm",
    "RU|Angarsk": "https://www.urbanrail.net/eu/ru/angarsk/angarsk.htm",
    "RU|Barnaul": "https://www.urbanrail.net/eu/ru/barnaul/barnaul.htm",
    "RU|Biysk": "https://www.urbanrail.net/eu/ru/biysk/biysk.htm",
    "RU|Chelyabinsk": "https://www.urbanrail.net/eu/ru/chelya/chelyabinsk.htm",
    "RU|Irkutsk": "https://www.urbanrail.net/eu/ru/irkutsk/irkutsk.htm",
    "RU|Izhevsk": "https://www.urbanrail.net/eu/ru/izhevsk/izhevsk.htm",
    "RU|Kaliningrad": "https://www.urbanrail.net/eu/ru/kaliningrad/kaliningrad.htm",
    "RU|Kazan": "https://www.urbanrail.net/eu/ru/kaz/kazan.htm",
    "RU|Krasnodar": "https://www.urbanrail.net/eu/ru/krasnodar/krasnodar.htm",
    "RU|Krasnoyarsk": "https://www.urbanrail.net/eu/ru/krasno/krasnoyarsk.htm",
    "RU|Kursk": "https://www.urbanrail.net/eu/ru/kursk/kursk.htm",
    "RU|Lipetsk": "https://www.urbanrail.net/eu/ru/lipetsk/lipetsk.htm",
    "RU|Magnitogorsk": "https://www.urbanrail.net/eu/ru/magnitogrosk/magnitogorsk.htm",
    "RU|Moscow": "https://www.urbanrail.net/eu/ru/mos/moskva.htm",
    "RU|Naberezhnyye Chelny": "https://www.urbanrail.net/eu/ru/nabchelny/naberezhnye-chelny.htm",
    "RU|Nizhnekamsk": "https://www.urbanrail.net/eu/ru/nizhnekamsk/nizhnekamsk.htm",
    "RU|Nizhniy Novgorod": "https://www.urbanrail.net/eu/ru/niz/nizhniy-novgorod.htm",
    "RU|Novosibirsk": "https://www.urbanrail.net/eu/ru/novosib/novosibirsk.htm",
    "RU|Novotroitsk": "https://www.urbanrail.net/eu/ru/novotroitsk/novotroitsk.htm",
    "RU|Omsk": "https://www.urbanrail.net/eu/ru/omsk/omsk.htm",
    "RU|Orel": "https://www.urbanrail.net/eu/ru/oryol/oryol.htm",
    "RU|Orsk": "https://www.urbanrail.net/eu/ru/orsk/orsk.htm",
    "RU|Osinniki": "https://www.urbanrail.net/eu/ru/osinniki/osinniki.htm",
    "RU|Pyatigorsk": "https://www.urbanrail.net/eu/ru/pyatigorsk/pyatigorsk.htm",
    "RU|Rostov-on-Don": "https://www.urbanrail.net/eu/ru/ros/rostov-na-donu.htm",
    "RU|Salavat": "https://www.urbanrail.net/eu/ru/salavat/salavat.htm",
    "RU|Samara": "https://www.urbanrail.net/eu/ru/sam/samara.htm",
    "RU|Saratov": "https://www.urbanrail.net/eu/ru/saratov/saratov.htm",
    "RU|Staryy Oskol": "https://www.urbanrail.net/eu/ru/staryi-oskol/staryi-oskol.htm",
    "RU|Taganrog": "https://www.urbanrail.net/eu/ru/taganrog/taganrog.htm",
    "RU|Tomsk": "https://www.urbanrail.net/eu/ru/tomsk/tomsk.htm",
    "RU|Tula": "https://www.urbanrail.net/eu/ru/tula/tula.htm",
    "RU|Ufa": "https://www.urbanrail.net/eu/ru/ufa/ufa.htm",
    "RU|Ust-Ilimsk": "https://www.urbanrail.net/eu/ru/ust-ilimsk/ust-ilimsk.htm",
    "RU|Vladivostok": "https://www.urbanrail.net/eu/ru/vladivostok/vladivostok.htm",
    "RU|Volchansk": "https://www.urbanrail.net/eu/ru/volchansk/volchansk.htm",
    "RU|Volgograd": "https://www.urbanrail.net/eu/ru/vol/volgograd.htm",
    "RU|Volzhskiy": "https://www.urbanrail.net/eu/ru/volzhskiy/volzhskiy.htm",
    "RU|Yaroslavl": "https://www.urbanrail.net/eu/ru/yaroslavl/yaroslavl.htm",
    "RU|Yekaterinburg": "https://www.urbanrail.net/eu/ru/yekatarin/yekaterinburg.htm",
    "RU|Zlatoust": "https://www.urbanrail.net/eu/ru/zlatoust/zlatoust.htm",
    "SA|Makkah": "https://www.urbanrail.net/as/mecca/makkah.htm",
    "SA|Riyadh": "https://www.urbanrail.net/as/riyadh/riyadh.htm",
    "SE|Gothenburg": "https://www.urbanrail.net/eu/se/goteborg/goteborg.htm",
    "SE|Lund": "https://www.urbanrail.net/eu/se/lund/lund.htm",
    "SE|Norrkoeping": "https://www.urbanrail.net/eu/se/norrkoeping/norrkoeping.htm",
    "SE|Stockholm": "https://www.urbanrail.net/eu/se/stockholm/stockhlm.htm",
    "SG|Singapore": "https://www.urbanrail.net/as/sing/singapore.htm",
    "SK|Bratislava": "https://www.urbanrail.net/eu/sk/bratislava/bratislava.htm",
    "SK|Kosice": "https://www.urbanrail.net/eu/sk/kosice/kosice.htm",
    "SN|Dakar": "https://www.urbanrail.net/af/dakar/dakar.htm",
    "TH|Bangkok": "https://www.urbanrail.net/as/bang/bangkok.htm",
    "TN|Tunis": "https://www.urbanrail.net/af/tunis/tunis.htm",
    "TR|Adana": "https://www.urbanrail.net/as/tr/adana/adana.htm",
    "TR|Ankara": "https://www.urbanrail.net/as/tr/ankara/ankara.htm",
    "TR|Antalya": "https://www.urbanrail.net/as/tr/antalya/antalya.htm",
    "TR|Bursa": "https://www.urbanrail.net/as/tr/bursa/bursa.htm",
    "TR|Eskisehir": "https://www.urbanrail.net/as/tr/eskisehir/eskisehir.htm",
    "TR|Gaziantep": "https://www.urbanrail.net/as/tr/gaziantep/gaziantep.htm",
    "TR|Istanbul": "https://www.urbanrail.net/as/tr/istanbul/istanbul.htm",
    "TR|Izmir": "https://www.urbanrail.net/as/tr/izmir/izmir.htm",
    "TR|Izmit": "https://www.urbanrail.net/as/tr/izmit/izmit.htm",
    "TR|Kayseri": "https://www.urbanrail.net/as/tr/kayseri/kayseri.htm",
    "TR|Konya": "https://www.urbanrail.net/as/tr/konya/konya.htm",
    "TR|Samsun": "https://www.urbanrail.net/as/tr/samsun/samsun.htm",
    "TW|Kaohsiung": "https://www.urbanrail.net/as/tw/kaoh/kaohsiung.htm",
    "TW|Taichung": "https://www.urbanrail.net/as/tw/taichung/taichung.htm",
    "TW|Taipei": "https://www.urbanrail.net/as/tw/taip/taipei.htm",
    "TW|Taoyuan": "https://www.urbanrail.net/as/tw/taip/taoyuan.htm",
    "UA|Avdiivka": "https://www.urbanrail.net/eu/ua/avdeevka/avdeevka.htm",
    "UA|Dnipro": "https://www.urbanrail.net/eu/ua/dnipro/dnipro.htm",
    "UA|Donetsk": "https://www.urbanrail.net/eu/ua/don/donetsk.htm",
    "UA|Druzhkivka": "https://www.urbanrail.net/eu/ua/druzhkivka/druzhkivka.htm",
    "UA|Horlivka": "https://www.urbanrail.net/eu/ua/horlivka/horlivka.htm",
    "UA|Kamyanske": "https://www.urbanrail.net/eu/ua/kamianske/kamianske.htm",
    "UA|Kharkiv": "https://www.urbanrail.net/eu/ua/kha/kharkiv.htm",
    "UA|Konotop": "https://www.urbanrail.net/eu/ua/konotop/konotop.htm",
    "UA|Kryvyy Rih": "https://www.urbanrail.net/eu/ua/kry/kryvy-rih.htm",
    "UA|Kyiv": "https://www.urbanrail.net/eu/ua/kiev/kyiv.htm",
    "UA|Luhansk": "https://www.urbanrail.net/eu/ua/luhansk/luhansk.htm",
    "UA|Lviv": "https://www.urbanrail.net/eu/ua/lviv/lviv.htm",
    "UA|Mariupol": "https://www.urbanrail.net/eu/ua/mariupol/mariupol.htm",
    "UA|Mykolayiv": "https://www.urbanrail.net/eu/ua/mykolaiv/mykolaiv.htm",
    "UA|Odesa": "https://www.urbanrail.net/eu/ua/odessa/odessa.htm",
    "UA|Vinnytsya": "https://www.urbanrail.net/eu/ua/vinnytsia/vinnytsia.htm",
    "UA|Yenakiieve": "https://www.urbanrail.net/eu/ua/yenakiieve/yenakiieve.htm",
    "UA|Yevpatoriya": "https://www.urbanrail.net/eu/ua/yevpatoria/yevpatoria.htm",
    "UA|Zaporizhzhya": "https://www.urbanrail.net/eu/ua/zaporizhia/zaporizhia.htm",
    "UA|Zhytomyr": "https://www.urbanrail.net/eu/ua/zhytomyr/zhytomyr.htm",
    "US|Atlanta": "https://www.urbanrail.net/am/atla/atlanta.htm",
    "US|Austin": "https://www.urbanrail.net/am/austin/austin.htm",
    "US|Baltimore": "https://www.urbanrail.net/am/balt/baltimore.htm",
    "US|Boston": "https://www.urbanrail.net/am/bost/boston.htm",
    "US|Buffalo": "https://www.urbanrail.net/am/buff/buffalo.htm",
    "US|Charlotte": "https://www.urbanrail.net/am/char/charlotte.htm",
    "US|Chicago": "https://www.urbanrail.net/am/chic/chicago.htm",
    "US|Cincinnati": "https://www.urbanrail.net/am/cinn/cincinnati.htm",
    "US|Cleveland": "https://www.urbanrail.net/am/clev/cleveland.htm",
    "US|Dallas": "https://www.urbanrail.net/am/dall/dallas.htm",
    "US|Denver": "https://www.urbanrail.net/am/denv/denver.htm",
    "US|Detroit": "https://www.urbanrail.net/am/detr/detroit.htm",
    "US|El Paso": "https://www.urbanrail.net/am/elpaso/el-paso.htm",
    "US|Honolulu": "https://www.urbanrail.net/am/hono/honolulu.htm",
    "US|Houston": "https://www.urbanrail.net/am/hous/houston.htm",
    "US|Jacksonville": "https://www.urbanrail.net/am/jack/jacksonville.htm",
    "US|Kansas City": "https://www.urbanrail.net/am/kansas/kansas-city.htm",
    "US|Las Vegas": "https://www.urbanrail.net/am/lveg/las-vegas.htm",
    "US|Little Rock": "https://www.urbanrail.net/am/little-rock/little-rock.htm",
    "US|Los Angeles": "https://www.urbanrail.net/am/lsan/los-angeles.htm",
    "US|Memphis": "https://www.urbanrail.net/am/memphis/memphis.htm",
    "US|Miami": "https://www.urbanrail.net/am/miam/miami.htm",
    "US|Milwaukee": "https://www.urbanrail.net/am/milwaukee/milwaukee.htm",
    "US|Minneapolis": "https://www.urbanrail.net/am/minn/minneapolis.htm",
    "US|Morgantown": "https://www.urbanrail.net/am/morg/morgantown.htm",
    "US|New Orleans": "https://www.urbanrail.net/am/new-orleans/new-orleans.htm",
    "US|New York City": "https://www.urbanrail.net/am/nyrk/new-york.htm",
    "US|Newark": "https://www.urbanrail.net/am/nj/new-jersey.htm",
    "US|Norfolk": "https://www.urbanrail.net/am/norfolk/norfolk.htm",
    "US|Oklahoma City": "https://www.urbanrail.net/am/oklahoma/oklahoma-city.htm",
    "US|Omaha": "https://www.urbanrail.net/am/omaha/omaha.htm",
    "US|Philadelphia": "https://www.urbanrail.net/am/phil/philadelphia.htm",
    "US|Phoenix": "https://www.urbanrail.net/am/phoenix/phoenix.htm",
    "US|Pittsburgh": "https://www.urbanrail.net/am/pitt/pittsburgh.htm",
    "US|Portland": "https://www.urbanrail.net/am/ptld/portland.htm",
    "US|Sacramento": "https://www.urbanrail.net/am/sacr/sacramento.htm",
    "US|Salt Lake City": "https://www.urbanrail.net/am/salt/salt-lake-city.htm",
    "US|San Diego": "https://www.urbanrail.net/am/sdie/san-diego.htm",
    "US|San Francisco": "https://www.urbanrail.net/am/snfr/san-francisco.htm",
    "US|San Jose": "https://www.urbanrail.net/am/sjos/san-jose.htm",
    "US|Santa Ana": "https://www.urbanrail.net/am/lsan/oc-streetcar.htm",
    "US|Seattle": "https://www.urbanrail.net/am/seat/seattle.htm",
    "US|St. Louis": "https://www.urbanrail.net/am/slou/saint-louis.htm",
    "US|St. Petersburg": "https://www.urbanrail.net/eu/ru/pet/petersburg.htm",
    "US|Tacoma": "https://www.urbanrail.net/am/tacoma/tacoma.htm",
    "US|Tampa": "https://www.urbanrail.net/am/tampa/tampa.htm",
    "US|Tucson": "https://www.urbanrail.net/am/tucson/tucson.htm",
    "US|Washington": "https://www.urbanrail.net/am/wash/washington.htm",
    "UZ|Samarkand": "https://www.urbanrail.net/as/uz/samarkand/samarkand.htm",
    "UZ|Tashkent": "https://www.urbanrail.net/as/uz/toshkent/toshkent.htm",
    "VE|Caracas": "https://www.urbanrail.net/am/cara/caracas.htm",
    "VE|Maracaibo": "https://www.urbanrail.net/am/mara/maracaibo.htm",
    "VE|Valencia": "https://www.urbanrail.net/am/vale/valencia.htm",
    "VN|Hanoi": "https://www.urbanrail.net/as/hanoi/hanoi.htm",
    "VN|Ho Chi Minh City": "https://www.urbanrail.net/as/hcmc/ho-chi-minh-city.htm",
    "ZA|Cape Town": "https://www.urbanrail.net/af/cape/capetown.htm",
    "ZA|Durban": "https://www.urbanrail.net/af/durban/durban.htm",
    "ZA|Johannesburg": "https://www.urbanrail.net/af/joburg/johannesburg.htm",
    "ZA|Pretoria": "https://www.urbanrail.net/af/joburg/pretoria.htm",
};
