// === WYMOGI WIZOWE dla paszportu PL ===
// Zrodlo: Wikipedia 'Visa requirements for Polish citizens' (parsowane). Pobrano: 2026-07-07.
// NIEURZEDOWE - przepisy sie zmieniaja, zweryfikuj w MSZ (odyseusz.gov.pl) przed podroza.
// Wartosci: liczba = dni bez wizy; 'visa free'; 'visa on arrival'; 'e-visa'; 'eta'; 'visa required'.
const VISA_PL = {"AD":"90","AE":"90","AF":"e-visa","AG":"180","AL":"90","AM":"180","AO":"30","AR":"90","AT":"visa free","AU":"eta","AZ":"e-visa","BA":"90","BB":"90","BD":"visa on arrival","BE":"visa free","BF":"e-visa","BG":"visa free","BH":"visa on arrival","BI":"visa on arrival","BJ":"e-visa","BN":"90","BO":"90","BR":"90","BS":"90","BT":"e-visa","BW":"e-visa","BY":"90","BZ":"30","CA":"eta","CD":"e-visa","CF":"visa required","CG":"visa required","CH":"visa free","CI":"e-visa","CL":"90","CM":"e-visa","CN":"30","CO":"90","CR":"90","CU":"e-visa","CV":"30","CY":"visa free","CZ":"visa free","DE":"visa free","DJ":"e-visa","DK":"visa free","DM":"90","DO":"90","DZ":"visa required","EC":"90","EE":"visa free","EG":"visa on arrival","ER":"visa required","ES":"visa free","ET":"visa on arrival","FI":"visa free","FJ":"120","FM":"90","FR":"visa free","GA":"e-visa","GB":"eta","GD":"90","GE":"visa free","GH":"visa required","GM":"90","GN":"e-visa","GQ":"e-visa","GR":"visa free","GT":"90","GW":"visa on arrival","GY":"e-visa","HN":"90","HR":"visa free","HT":"90","HU":"visa free","ID":"visa on arrival","IE":"visa free","IL":"eta","IN":"e-visa","IQ":"e-visa","IR":"e-visa","IS":"visa free","IT":"visa free","JM":"30","JO":"visa on arrival","JP":"90","KE":"eta","KG":"60","KH":"visa on arrival","KI":"90","KM":"visa on arrival","KN":"eta","KP":"visa required","KR":"eta","KW":"visa on arrival","KZ":"30","LA":"visa on arrival","LB":"visa on arrival","LC":"90","LI":"visa free","LK":"visa on arrival","LR":"e-visa","LS":"e-visa","LT":"visa free","LU":"visa free","LV":"visa free","LY":"e-visa","MA":"90","MC":"90","MD":"90","ME":"90","MG":"visa on arrival","MH":"90","MK":"90","ML":"visa required","MM":"e-visa","MN":"30","MR":"e-visa","MT":"visa free","MU":"90","MV":"visa on arrival","MW":"visa on arrival","MX":"180","MY":"90","MZ":"visa on arrival","NA":"visa on arrival","NE":"visa required","NG":"e-visa","NI":"90","NL":"visa free","NO":"visa free","NP":"visa on arrival","NR":"visa required","NZ":"eta","OM":"e-visa","PA":"90","PE":"90","PG":"e-visa","PH":"30","PK":"e-visa","PT":"visa free","PW":"90","PY":"90","QA":"90","RO":"visa free","RS":"90","RU":"e-visa","RW":"visa on arrival","SA":"visa on arrival","SB":"90","SC":"90","SD":"visa required","SE":"visa free","SG":"90","SI":"visa free","SK":"visa free","SL":"visa on arrival","SM":"90","SN":"90","SO":"e-visa","SR":"e-visa","SS":"e-visa","ST":"15","SV":"90","SY":"e-visa","SZ":"30","TD":"e-visa","TG":"e-visa","TH":"60","TJ":"30","TL":"90","TM":"visa required","TN":"90","TO":"90","TR":"90","TT":"90","TV":"90","TZ":"visa on arrival","UA":"90","UG":"e-visa","US":"eta","UY":"90","UZ":"30","VA":"visa free","VC":"30","VE":"90","VN":"45","VU":"90","WS":"90","YE":"visa required","ZA":"30","ZM":"30","ZW":"visa on arrival"};
const VISA_PL_DATE = "2026-07-07";
// Korekty reczne (nadpisuja VISA_PL). Zrodlo: MSZ. Dopisz kraj gdy dataset zalega.
const VISA_PL_OVERRIDES = {
    // Dataset zrodlowy nie ma tych dwoch (brak uznania/statusu w bazie, z ktorej leci VISA_PL),
    // a paszport PL wjezdza do obu bez wizy na 90 dni.
    "TW": "90", // Tajwan
    "XK": "90"  // Kosowo
};
